import { useState } from 'react'
import { ArrowUpRight, CaretDown, Check, CheckCircle, EnvelopeSimple, InstagramLogo, List, MagicWand, MapPin, Megaphone, MonitorPlay, Palette, Phone, QrCode, Sparkle, Target, X } from '@phosphor-icons/react'
import './App.css'

const whatsappUrl = 'https://wa.me/5511994259127?text=Ol%C3%A1%20ORIZON!%20Quero%20conhecer%20os%20servi%C3%A7os.'
const services = [
  { number: '01', icon: MonitorPlay, title: 'Sites que posicionam', text: 'Estruturas rápidas, responsivas e pensadas para transformar visita em conversa.', tag: 'Web design' },
  { number: '02', icon: QrCode, title: 'Cardápio digital', text: 'Uma experiência simples para o cliente pedir, descobrir e voltar ao seu negócio.', tag: 'Restaurantes' },
  { number: '03', icon: Palette, title: 'Marca com presença', text: 'Identidade visual, logo e direção criativa para a sua empresa ser reconhecida.', tag: 'Branding' },
  { number: '04', icon: Megaphone, title: 'Atração que performa', text: 'Landing pages, tráfego pago e conteúdo para colocar sua oferta na frente das pessoas certas.', tag: 'Marketing' },
]
const faqs = [
  ['Vocês atendem empresas de qualquer segmento?', 'Sim. Atuamos com negócios locais, serviços e empresas em crescimento. Para restaurantes, também criamos experiências digitais e estratégias de recorrência mais específicas.'],
  ['Quanto tempo leva para colocar um site no ar?', 'Cada projeto tem um ritmo, mas uma landing page costuma sair em poucos dias úteis. Antes de começar, apresentamos um cronograma claro e as etapas de aprovação.'],
  ['A ORIZON também cuida do marketing depois do lançamento?', 'Sim. Podemos assumir a evolução do site, campanhas de tráfego pago, conteúdo para Instagram e as próximas decisões de comunicação da marca.'],
]

function Logo({ light = false }) { return <a className={`logo ${light ? 'logo-light' : ''}`} href="#inicio" aria-label="ORIZON, voltar ao início"><span className="logo-mark" aria-hidden="true"><span /></span><span>ORIZON</span></a> }
function SectionLabel({ children }) { return <p className="section-label"><span />{children}</p> }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  const [submitted, setSubmitted] = useState(false)
  const closeMenu = () => setMenuOpen(false)
  return <div className="site-shell">
    <header className="site-header"><div className="container header-inner"><Logo /><nav className={`main-nav ${menuOpen ? 'is-open' : ''}`} aria-label="Navegação principal"><a href="#solucoes" onClick={closeMenu}>Soluções</a><a href="#orizon-loyalty" onClick={closeMenu}>ORIZON Loyalty</a><a href="#processo" onClick={closeMenu}>Como fazemos</a><a href="#contato" onClick={closeMenu}>Contato</a></nav><a className="button button-small button-outline header-cta" href={whatsappUrl} target="_blank" rel="noreferrer">Falar com a ORIZON <ArrowUpRight size={16} weight="bold" /></a><button className="menu-toggle" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menuOpen}>{menuOpen ? <X size={24} /> : <List size={24} />}</button></div></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-grid" aria-hidden="true" /><div className="container hero-content"><div className="hero-copy reveal"><SectionLabel>ESTRATÉGIA + DESIGN + TECNOLOGIA</SectionLabel><h1>Ideias boas merecem uma <em>presença</em> à altura.</h1><p className="hero-text">A ORIZON cria marcas, sites e experiências digitais que tornam negócios mais claros, desejados e fáceis de escolher.</p><div className="hero-actions"><a className="button button-primary" href="#contato">Começar um projeto <ArrowUpRight size={18} weight="bold" /></a><a className="text-link" href="#solucoes">Explorar soluções <ArrowUpRight size={17} /></a></div><div className="hero-proof"><CheckCircle size={18} weight="fill" /><span>Projetos sob medida para negócios que querem crescer</span></div></div><div className="hero-visual reveal delay-1" aria-label="Painel conceitual de uma experiência digital ORIZON"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-label label-top"><Sparkle size={15} /> feito para ser lembrado</div><div className="dashboard-card"><div className="dashboard-top"><span className="window-dots"><i /><i /><i /></span><span className="dashboard-status"><span /> ao vivo</span></div><div className="dashboard-brand">ORIZON<span>.</span></div><div className="dashboard-heading">Seu próximo cliente<br /><strong>já está por perto.</strong></div><div className="dashboard-chart"><span className="chart-line" /><i className="chart-point point-one" /><i className="chart-point point-two" /><i className="chart-point point-three" /></div><div className="dashboard-footer"><span>alcance qualificado</span><strong>+68.4%</strong></div></div><div className="visual-label label-bottom"><Target size={15} /> clareza que converte</div></div></div><div className="container hero-foot"><span>São Paulo · Brasil</span><span className="scroll-note"><span className="scroll-line" /> role para descobrir</span><span>ORIZON / 2026</span></div></section>
      <section className="intro section-space"><div className="container intro-grid"><SectionLabel>POR QUE A ORIZON</SectionLabel><div className="intro-content"><h2>Não é só sobre aparecer.<br /><span>É sobre fazer sentido.</span></h2><p>Em um mundo cheio de marcas disputando atenção, presença sem intenção vira ruído. A ORIZON une estratégia, criatividade e tecnologia para transformar o que sua empresa faz em uma experiência que as pessoas entendem, lembram e escolhem.</p><a className="text-link" href="#processo">Conheça nosso jeito de trabalhar <ArrowUpRight size={17} /></a></div></div></section>
      <section className="services section-space" id="solucoes"><div className="container"><div className="section-heading"><div><SectionLabel>O QUE FAZEMOS</SectionLabel><h2>Do primeiro olhar<br /><span>ao próximo passo.</span></h2></div><p>Uma base digital consistente para você comunicar melhor, atrair as pessoas certas e crescer com mais intenção.</p></div><div className="services-grid">{services.map(({ number, icon: Icon, title, text, tag }) => <article className="service-card" key={number}><div className="service-card-top"><span className="service-number">{number}</span><Icon size={27} weight="light" /></div><h3>{title}</h3><p>{text}</p><span className="service-tag">{tag}</span><ArrowUpRight className="card-arrow" size={19} /></article>)}</div></div></section>
      <section className="loyalty-section section-space" id="orizon-loyalty"><div className="container loyalty-grid"><div className="loyalty-copy"><SectionLabel>UM PRODUTO ORIZON</SectionLabel><h2>Seu restaurante tem clientes.<br /><em>A ORIZON ajuda a fazer eles voltarem.</em></h2><p>O ORIZON Loyalty é nossa plataforma de fidelização e inteligência para restaurantes. Ela transforma dados de consumo em relacionamento, campanhas e decisões mais inteligentes.</p><a className="button button-dark" href="#contato">Quero conhecer o produto <ArrowUpRight size={18} weight="bold" /></a></div><div className="loyalty-panel"><div className="loyalty-panel-head"><span><span className="mini-mark" /> ORIZON / loyalty</span><span className="panel-live"><span /> conectado</span></div><div className="metric-main"><span>clientes ativos</span><strong>2.846</strong><small>+12,8% <span>este mês</span></small></div><div className="metric-bars"><i style={{ height: '46%' }} /><i style={{ height: '62%' }} /><i style={{ height: '55%' }} /><i style={{ height: '78%' }} /><i style={{ height: '68%' }} /><i className="bar-highlight" style={{ height: '92%' }} /><i style={{ height: '84%' }} /></div><div className="insight"><div className="insight-icon"><MagicWand size={18} weight="fill" /></div><div><span>ORIZON insight</span><p>80 clientes estão há 45 dias sem voltar. Uma campanha de retorno pode reativar esse grupo.</p></div><ArrowUpRight size={17} /></div></div></div></section>
      <section className="process section-space" id="processo"><div className="container"><div className="section-heading process-heading"><div><SectionLabel>COMO FAZEMOS</SectionLabel><h2>Estratégia antes<br /><span>de estética.</span></h2></div><p>Cada projeto começa entendendo o negócio, o momento e a ambição por trás dele.</p></div><div className="process-list"><div><span>01</span><div><h3>Entender</h3><p>Investigamos o contexto, as pessoas e o problema real a resolver.</p></div><Check size={21} /></div><div><span>02</span><div><h3>Construir</h3><p>Desenhamos a estratégia e criamos a experiência que dá forma à ideia.</p></div><Check size={21} /></div><div><span>03</span><div><h3>Evoluir</h3><p>Colocamos no ar, medimos o que importa e melhoramos continuamente.</p></div><Check size={21} /></div></div></div></section>
      <section className="faq section-space"><div className="container faq-grid"><div><SectionLabel>AINDA COM DÚVIDAS?</SectionLabel><h2>Vamos deixar<br /><span>tudo claro.</span></h2><p>Um bom projeto começa com uma conversa simples. Sem apresentação pronta, sem complicação.</p><a className="text-link" href={whatsappUrl} target="_blank" rel="noreferrer">Conversar pelo WhatsApp <ArrowUpRight size={17} /></a></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'is-open' : ''}`} key={question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)} aria-expanded={openFaq === index}><span>{question}</span><CaretDown size={19} /></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></div></section>
      <section className="contact-section" id="contato"><div className="container contact-grid"><div className="contact-copy"><SectionLabel>VAMOS CONVERSAR</SectionLabel><h2>O próximo capítulo<br /><em>começa aqui.</em></h2><p>Conte um pouco sobre o que você está construindo. A gente responde com ideias, caminhos e os próximos passos.</p><div className="contact-details"><a href="mailto:ola@orizon.ag"><EnvelopeSimple size={19} /> ola@orizon.ag</a><a href={whatsappUrl} target="_blank" rel="noreferrer"><Phone size={19} /> (11) 99425-9127</a><span><MapPin size={19} /> São Paulo, SP</span></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><label>Seu nome<input type="text" name="name" placeholder="Como podemos te chamar?" required /></label><label>Seu melhor e-mail<input type="email" name="email" placeholder="voce@empresa.com" required /></label><label>Como podemos ajudar?<select name="project" defaultValue=""><option value="" disabled>Escolha uma opção</option><option>Site ou landing page</option><option>Marca e identidade visual</option><option>Marketing e tráfego pago</option><option>ORIZON Loyalty</option></select></label><label>Conte mais (opcional)<textarea name="message" rows="3" placeholder="Um pouco do contexto já ajuda bastante." /></label><button className="button button-primary" type="submit">{submitted ? <>Mensagem preparada <CheckCircle size={18} weight="fill" /></> : <>Enviar mensagem <ArrowUpRight size={18} weight="bold" /></>}</button>{submitted && <p className="form-note">Recebemos seu interesse. Para garantir uma resposta rápida, você também pode falar direto pelo WhatsApp.</p>}</form></div></section>
    </main>
    <footer className="site-footer"><div className="container footer-top"><Logo light /><p>Presença digital para negócios<br />que querem ir mais longe.</p><div className="footer-links"><a href="#solucoes">Soluções</a><a href="#orizon-loyalty">ORIZON Loyalty</a><a href="#contato">Contato</a></div><a className="social-link" href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram da ORIZON"><InstagramLogo size={21} /></a></div><div className="container footer-bottom"><span>© 2026 ORIZON. Todos os direitos reservados.</span><span>Estratégia para o que vem a seguir.</span></div></footer><a className="whatsapp-float" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Falar com a ORIZON pelo WhatsApp"><Phone size={23} weight="fill" /></a>
  </div>
}